blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, \
    BlogDeleteView, Toggle_Activity_Blog, BlogDraftListView


app_name = 'blog'


urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('drafts', BlogDraftListView.as_view(), name='blog_drafts'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/toggle/<slug:slug>/', Toggle_Activity_Blog.as_view(), name='toggle_activity_blog'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('user_auth.urls', namespace='user_auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import itertools

from django.db import models
from django.utils.text import slugify

NULLABLE = {'null': True, 'blank': True}


# Create your models here.

class Blog(models.Model):
    """
    модель блоговой записи содержит следующие поля:

    заголовок
    slug (CharField)
    содержимое
    превью (изображение)
    дата создания
    признак публикации
    количество просмотров
    """
    '''
    title
    slug
    description
    preview
    is_active
    created_at
    is_published
    count_view
    '''
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(verbose_name='Превью', upload_to='blog/', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активная')
    created_at = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Опубликована')
    count_view = models.IntegerField(verbose_name='Количество просмотров', default=0)



    def __str__(self):
        return f' Запись блога ({self.title}, Дата создания:{self.created_at}, Количество просмотров:{self.count_view})'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()
        return super().save(*args, **kwargs)

    def _generate_slug(self):
        slug_candidate = slugify(self.title, allow_unicode=False)
        if not slug_candidate:
            slug_candidate = "s"
        for i in itertools.count(1):
            if not Blog.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_candidate, i)
        self.slug = slug_candidate
        return self.slug


    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('title', 'created_at',)

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views import generic, View

from blog.models import Blog
from config.settings import EMAIL_HOST_USER


# Create your views here.

class BlogDetailView(generic.DetailView):
    model = Blog
    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        contex_data['title'] = self.get_object()
        contex_data['text'] = self.get_object()
        return contex_data

    # def get_object(self, queryset=None):
    def get(self, request, *args, **kwargs):
        self.object = super().get_object()
        self.object.count_view += 1
        # print("Увеличение счетчика")
        self.object.save()
        context = self.get_context_data(object=self.object)
        if self.object.count_view == 100:

            # Посылаем email, когда счетчик достигнет 100
            subject = f"Вашу статью прочитали {self.object.count_view} раз!"
            message_body = f"Количество просмотров статьи {self.object.title} достигло {self.object.count_view}"
            send_mail(
            subject,
            message_body,
            EMAIL_HOST_USER,
            [EMAIL_HOST_USER],
            fail_silently=False,
            )
        return self.render_to_response(context)

class BlogListView(generic.ListView):
    model = Blog
    extra_context = {
        'title': 'Наши блог',
        'text': "Наш блог"
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True, is_published=True).order_by("-created_at", "title")
        return queryset

class BlogDraftListView(generic.ListView):
    model = Blog
    extra_context = {
        'title': 'Черновики статей',
        'text': "Черновики статей"
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True, is_published=False).order_by("-created_at", "title")
        return queryset


class BlogCreateView(generic.CreateView):
    model = Blog
    fields = ('title', 'description', 'preview', 'is_active', 'is_published')
    success_url = reverse_lazy('blog:blogs')


class BlogUpdateView(generic.UpdateView):
    model = Blog
    fields = ('title', 'description', 'preview', 'is_active', 'is_published')
    # success_url = reverse_lazy('blog:blogs')
    def get_success_url(self):
        return reverse('blog:blog', args=[self.object.slug])


class BlogDeleteView(generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs')


class Toggle_Activity_Blog(View):
    def get(request, *args, slug, **kwargs):
        text = ""
        blogs = get_object_or_404(Blog, slug=slug)
        if blogs.is_active:
            blogs.is_active = False
            subject = "Статья деактивирована"
            message_body = f"Статья {blogs} деактивирована"
        else:
            blogs.is_active = True
            subject = "Статья активирована"
            message_body = f"Статья {blogs} активирована"
        blogs.save()
        send_mail(
            subject,
            message_body,
            EMAIL_HOST_USER ,
            [EMAIL_HOST_USER],
            fail_silently=False,
        )
        return redirect(reverse('blog:blog', args=[blogs.slug]))

blog/templates/blog/blog_confirm_delete.html
{% extends 'products/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены, что хотите удалить статью? "{{ object }}"<br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен"  &raquo;>
                </form>
                <div class="card-footer">
                    <a href="{% url 'blog:blogs' %}" class="btn btn-primary">Наш блог</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'products/base.html' %}
{% block content %}
    {% include 'blog/includes/blog.html' %}
    {% include 'blog/includes/buttons.html' %}
{% endblock content %}

blog/templates/blog/blog_form.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить статью{% else %}Создать статью{% endif %}"  &raquo;>
                </form>
                <div class="card-footer">
                    <a href="{% url 'blog:blogs' %}" class="btn btn-primary">Наш блог</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'products/base.html' %}
{% load functions %}
{% block content %}
<diov class="col-12">
    <a href="{% url 'blog:blogs' %}" class ='btn btn-primary' m-2>Все статьи &raquo;</a>
    <a href="{% url 'blog:blog_drafts' %}" class ='btn btn-primary' m-2>Черновики статей &raquo;</a>
</diov>
    <br>
    <br>
<diov class="col-12">
    <a href="{% url 'blog:blog_create' %}" class ='btn btn-primary' m-2>Добавить статью &raquo;</a>
</diov>
{% for object in object_list %}
    <div class="row">
     {% include 'blog/includes/blog.html' %}
    </div>
    <a class="btn btn-secondary" href={% url 'blog:blog' object.slug %}>Перейти &raquo;</a>
{% endfor %}
{% endblock content %}