blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, \
    BlogDeleteView, Toggle_Activity_Blog, BlogDraftListView


app_name = 'blog'


urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('drafts', BlogDraftListView.as_view(), name='blog_drafts'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/toggle/<slug:slug>/', Toggle_Activity_Blog.as_view(), name='toggle_activity_blog'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('user_auth.urls', namespace='user_auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from user_auth.apps import UserAuthConfig
from user_auth.views import ProfileUpdateView, RegisterView, generate_new_password, UserForgotPasswordView, \
    UserPasswordResetConfirmView, UserRegisterView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmedView, \
    EmailConfirmationFailedView

app_name = UserAuthConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='user_auth/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', RegisterView.as_view(), name='register'),
    path('register/', UserRegisterView.as_view(), name='register'),

    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),


    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    ]

user_auth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# from products.models import NULLABLE
NULLABLE = {'null': True, 'blank': True}

# Create your models here.

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users_auth/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)
    # verification_kod = models.IntegerField(verbose_name="код подтверждения", **NULLABLE)
    # is_verify = models.BooleanField(verbose_name='прошел верификацию', default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}" # , {'верифицирован' if self.is_verify else 'неверифицирован'}"

    # class Meta:
    #     verbose_name = 'Пользователь'
    #     verbose_name_plural = 'Пользователи'
    #     ordering = ('email',)

user_auth/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, SetPasswordForm, PasswordResetForm
from django import forms

from products.forms import FormStyleMixin
from user_auth.models import User


class UserForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForgotPasswordForm(FormStyleMixin, PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(FormStyleMixin, SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

user_auth/views.py
from random import sample
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View

from config import settings
from user_auth.models import User
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView, TemplateView
from user_auth.forms import UserForm, UserRegisterForm, UserForgotPasswordForm, UserSetNewPasswordForm


# Create your views here.
class UserIsNotAuthenticated(UserPassesTestMixin):
    """Миксин для запрета регистрации авторизованных юзеров"""
    def test_func(self):
        if self.request.user.is_authenticated:
            messages.info(self.request, 'Вы уже авторизованы. Вы не можете посетить эту страницу.')
            raise PermissionDenied
        return True

    def handle_no_permission(self):
        return redirect('home')

class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'user_auth/user_password_reset.html'
    success_url = reverse_lazy('products:index')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлено на ваш email'
    subject_template_name = 'user_auth/email/password_subject_reset_mail.txt'
    email_template_name = 'user_auth/email/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'user_auth/user_password_set_new.html'
    success_url = reverse_lazy('products:index')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context
class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('user_auth:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('user_auth:email_confirmed')
        else:
            return redirect('user_auth:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    template_name = 'user_auth/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'user_auth/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'user_auth/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context
class UserRegisterView(SuccessMessageMixin, CreateView):
    """
    Представление регистрации на сайте с формой регистрации
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('products:index')
    template_name = 'user_auth/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('user_auth:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = get_current_site(self.request)
        domain = current_site.domain
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{domain}{activation_url}',
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )
        return redirect('user_auth:email_confirmation_sent')
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('products:index')
    template_name = 'user_auth/register.html'

    def form_valid(self, form):
        new_user = form.save()
        # verification_link = _make_hash_value(request.user)

        verification_kod = "".join(sample("".join([str(i) for i in range(0,10)]), 4))

        verification_link=""
        message = f"""Для завершения регистрации пройдите
        по следующей ссылке, чтобы подтвердить свой
        адрес электронной почты: < a href = "{{ verification_link }}" > Подтвердить < / a >"""

        send_mail(
            subject='Вы начали процедуру регистрации',
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)

def generate_new_password(request):
    password = "".join(sample("".join([str(i) for i in range(0,10)]) + "*+-_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", 10))
    request.user.set_password(password)
    request.user.save()
    send_mail(
        subject='Новый пароль',
        message=f'Вам установлен новый пароль:\n{password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    return redirect(reverse('user_auth:login'))

user_auth/templates/user_auth/email_confirmation_failed.html
{% extends 'products/base.html' %}

{% block content %}
<h3>{{ title }}</h3>
{% endblock %}

user_auth/templates/user_auth/email_confirmation_sent.html
{% extends 'products/base.html' %}

{% block content %}
<h3>{{ title }}</h3>
{% endblock %}

user_auth/templates/user_auth/email_confirmed.html
{% extends 'products/base.html' %}

{% block content %}
<h3>{{ title }}</h3>
{% endblock %}

user_auth/templates/user_auth/login.html
{% extends 'products/base.html' %}

{% block content %}
<div class="row"
<div class="col-3">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                    </form>
                </div>
                <div class="card-footer">
            Заполните здесь свои данные
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

user_auth/templates/user_auth/register.html
{% extends 'products/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                    <form method="post">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </div>
                    <div class="card-footer">
                    После регистрации вам будет направлено письмо для подтверждения адреса.
                        {% if user.is_authenticated %}
                        <a href={% url "user_auth:generate_new_password" %} class="btn btn-info"> Сгенерировать новый пароль</a>
                        {% endif %}
                    </div>
                    </form>
            </div>
        </div>
    </div>

{% endblock %}

user_auth/templates/user_auth/user_auth_form.py.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

user_auth/templates/user_auth/user_form.html
{% extends 'products/base.html' %}

{% block content %}
<div class="row"
<div class="col-3">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
            Вход
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

user_auth/templates/user_auth/user_password_reset.html
{% extends 'products/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>
{% endblock %}

user_auth/templates/user_auth/user_password_set_new.html
{% extends 'products/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Установить новый пароль</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
            </form>
        </div>
    </div>
{% endblock %}