blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, \
    BlogDeleteView, Toggle_Activity_Blog, BlogDraftListView


app_name = 'blog'


urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('drafts', BlogDraftListView.as_view(), name='blog_drafts'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/toggle/<slug:slug>/', Toggle_Activity_Blog.as_view(), name='toggle_activity_blog'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('user_auth.urls', namespace='user_auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

# from products.views import about , index, contact, gallery,
from products.views import ProductDetailView, ProductsListView, ProductsCreateView, \
     ProductsUpdateView, ProductsDeleteView, ProductsNotPublishedView, toggle_activity_product, GetIndex, GetContact, \
    GetAbout, GetGallery, CategoryUpdateView, CategoryCreateView, CategoryDetailView, \
    CategoriesListView, CategoryDeleteView, toggle_activity_category
from products.views import VersionDetailView, VersionsListView, VersionCreateView, \
    VersionUpdateView, Toggle_Activity_Version, VersionDeleteView, VersionsDraftListView
from products.views import error

app_name = 'products'

urlpatterns = [
    path('index/', GetIndex.as_view(), name='index'),
    path('', GetAbout.as_view(), name='about'),
    path('gallery/', cache_page(60)(GetGallery.as_view()), name='gallery'),
    path('contact/', GetContact.as_view(), name='contact'),

    path('products/', never_cache()(ProductsListView.as_view()), name='products'),
    path('products/not_published', ProductsNotPublishedView.as_view(), name='products_not_published'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('products/create/', ProductsCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductsUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductsDeleteView.as_view(), name='product_delete'),
    path('products/toggle/<int:pk>/', toggle_activity_product, name='toggle_activity_product'),
    path('products/error/', error, name='error'),

    path('categories/', CategoriesListView.as_view(), name='categories'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category/toggle/<int:pk>/', toggle_activity_category, name='toggle_activity_category'),

    path('versions/', VersionsListView.as_view(), name='versions'),
    path('versions/draft/', VersionsDraftListView.as_view(), name='versions_draft'),
    path('version/<int:pk>/', VersionDetailView.as_view(), name='version'),
    # path('version/create/', VersionCreateView.as_view(), name='version_create'),
    path('version/update/<int:pk>/', VersionUpdateView.as_view(), name='version_update'),
    path('version/delete/<int:pk>/', VersionDeleteView.as_view(), name='version_delete'),
    path('version/toggle/<int:pk>/', Toggle_Activity_Version.as_view(), name='toggle_activity_version'),

    # path('index/', index, name='index'),
    # path('about/', about, name='about'),
    # path('gallery/', gallery, name='gallery'),
    # path('contact/', contact, name='contact'),
]

products/models.py
from django.core.exceptions import ValidationError
from django.db import models
from user_auth.models import User

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class Category(models.Model):
    """
    Наименование
    Описание
    """
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активный')
    # created_at = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name', )

class Products(models.Model):
    """
    Наименование
    Описание
    Изображение (превью)
    Категория
    Цена за покупку
    Дата создания
    Дата последнего изменения
    user
    name
    description
    image
    category
    price
    created_data
    last_changed_data
    is_active
    user
    is_published
    """
    # user = User.objects.filter(pk=2)
    name = models.CharField(max_length=150, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(verbose_name='Превью', upload_to='products/', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField(verbose_name='Цена', **NULLABLE)
    created_data = models.DateTimeField(verbose_name='Дата создания')
    last_changed_data = models.DateTimeField(verbose_name='Дата последнего изменения')
    is_active = models.BooleanField(default=True, verbose_name='активный')
    user = models.ForeignKey(User, verbose_name='пользователь-автор', default=None, on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='опубликован')

    def __str__(self):
        # return f'{self.id} {self.name}, {self.category}, {self.price}'
        return f'{self.name}'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('name', 'price')
        permissions = {
            ("set_published_status", "can published product"),
            ("set_description_status", "can change description product"),
            ("set_category_status", "can change category product")
            # ("set_publ_category_descr_status", "can change published product, description, category product")
        }

class Version(models.Model):
    """
    модель «Версия» содержит следующие поля:

    продукт,
    номер версии,
    название версии,
    признак текущей версии.
    При наличии активной версии реализовать вывод в список продуктов информации об активной версии.
    product
    version_number
    version_title
    is_active

    """
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name="Название продукта")
    version_number = models.IntegerField(verbose_name="Номер версии", **NULLABLE)
    version_title = models.CharField(max_length=150, verbose_name="Наименование версии", **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f"Версия № {self.version_number}, {self.version_title}"

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


    def save(self, *args, **kwargs):
        # проверяем, есть ли уже активная версия для этого продукта
        if self.is_active and Version.objects.filter(product=self.product, is_active=True).exclude(pk=self.pk).exists():
            raise ValidationError('Нельзя добавить более одной активной версии для данного продукта.')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)

products/forms.py
from django import forms
from django.forms import BaseInlineFormSet, inlineformset_factory
from django.shortcuts import get_object_or_404

from products.models import Category, Products, Version


LIST_FORBIDDEN_WORD =["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

def is_text_valid(text:str) -> bool:
    """
    :param text:
    :return: True, if text does not contain forbidden words
    """
    text = text.lower()
    for word in LIST_FORBIDDEN_WORD:
        if text.find(word, 0, len(text)) != -1:
            return False
    return True

# class VersionFormSet(BaseInlineFormSet):
#     def clean(self):
#         super().clean()
#         curent_version_count = 0
#         for form in self.forms:
#             if not form.is_valid():
#                 return
#             if form.cleaned_data and form.cleaned_data.get('is_current_version'):
#                 curent_version_count += 1
#             if curent_version_count > 1:
#                 raise form.ValidationError('Нельзя добавить более одной активной версии')
# ProductVersionFormSet = inlineformset_factory(
#     parent_model=Products,
#     model=Version,
#     form=VersionFormSet,
#     extra=1
# )

class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VersionForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        # Задаем класс для кнопки "Создать версию"
        self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['is_active'].label_attrs = {'class': 'form-check-label'}

    def clean_is_active(self):
        """
        нельзя добавить более одной активной версии
        """
        is_active = self.cleaned_data['is_active']
        product = self.cleaned_data['product']
        if self.instance.product:
            if is_active and self.instance.product.version_set.filter(is_active=True).exclude(id=self.instance.id).exists():
                raise forms.ValidationError('Нельзя добавить более одной активной версии')
        return is_active
    # def save(self, commit=True):
    #     super(VersionForm, self).save()

    # def save(self, commit=True):
    #     version = super().save(commit=False)
    #     product_id = self.data.get('product')
    #     if product_id:
    #         product = get_object_or_404(Products, id=product_id)
    #         version.product = product
    #     if commit:
    #         version.save()
    #     return version

class CategoryForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        # Задаем класс для кнопки "Создать версию"
        self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['is_active'].label_attrs = {'class': 'form-check-label'}

class ProductsFormCut(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Products
        exclude = ['is_published', 'description', 'category']

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
            # Задаем класс для кнопки "Создать версию"
            self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'})
            self.fields['is_active'].label_attrs = {'class': 'form-check-label'}
            self.fields['is_published'].widget.attrs.update({'class': 'form-check-input'})
            self.fields['is_published'].label_attrs = {'class': 'form-check-label'}
class ProductsForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Products
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        # Задаем класс для кнопки "Создать версию"
        self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['is_active'].label_attrs = {'class': 'form-check-label'}
        self.fields['is_published'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['is_published'].label_attrs = {'class': 'form-check-label'}

    def clean_name(self):
        """
        нельзя добавлять слова: казино, криптовалюта, крипта, биржа, дешево, бесплатно, обман, полиция, радар
        """
        name = self.cleaned_data['name']
        if not is_text_valid(name):
            raise forms.ValidationError('Название не должно содержать словa: ' + ", ".join(LIST_FORBIDDEN_WORD))
        return name

    def clean_description(self):
        """
        нельзя добавлять слова: казино, криптовалюта, крипта, биржа, дешево, бесплатно, обман, полиция, радар
        """
        description = self.cleaned_data['description']
        if not is_text_valid(description):
            raise forms.ValidationError('Описание товара не должно содержать словa: ' + ", ".join(LIST_FORBIDDEN_WORD))
        return description

    

products/templates/products/about.html
{% extends 'products/base.html' %}
    {% block content %}
        <h1>{{ text }}</h1>
    {% if current_user_name %}
        Добро пожаловать, {{ current_user_name.email }}!
    {% else %}
        Необходимо войти в систему.
    {% endif %}
    {% endblock content %}

products/templates/products/category_confirm_delete.html
{% extends 'products/base.html' %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены, что хотите удалить категорию? При удалении категории также будут удалены все товары, относящиеся к этой категории. "{{ object }}"<br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен"  &raquo;>
                </form>
                <div class="card-footer">
                    <a href="{% url 'products:products' %}" class="btn btn-primary">Главная</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

products/templates/products/category_detail.html
{% extends 'products/base.html' %}
{% block content %}
<h3>{{  text }}</h3>
    <div class="card" style="width: 24rem;">
          <div class="card-body">
                <h5 class="card-title">{{ object.name }}</h5>
                <p class="card-text">{{ object.description  }}</p>
                <div class="card-footer">

                    <diov class="col-12">
                        <a href="{% url 'products:category_create' %}" class ='btn btn-primary' m-2>Создать категорию &raquo;</a>
                    </diov>
                    <a href="{% url 'products:toggle_activity_category' object.pk %}" class="btn btn-warning float-rigth">
                            {% if object.is_active %}Деактивировать
                            {% else %}Активировать
                            {% endif %} &raquo;</a>
                </div>
                    <a href="{% url 'products:products' %}" class="btn btn-primary">Главная &raquo;</a>
          </div>
    </div>
{% endblock content %}

products/templates/products/category_form.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить категорию товара{% else %}Создать категорию товара{% endif %}"  &raquo; >
                </form>
                <div class="card-footer">
                    <a href="{% url 'products:categories' %}" class="btn btn-primary">Все категории</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

products/templates/products/contact.html
{% extends 'products/base.html' %}

    {% block content %}

        <h1>{{ text }}</h1>
    {% endblock content %}

products/templates/products/error.html
{% extends 'products/base.html' %}

    {% block content %}

        <h4>{{ text }}</h4>
        <h4>{{ error_message }}</h4>

    {% endblock content %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load functions %}
<!DOCTYPE html>
<html lang="en">
<head>


</head>
    <body>
    {% block content %}


    <h1>Последние 5 товаров</h1>
        <table>

            {% for obj in objects %}
                <tr>
                    <td>

                     <p><h3>{% get_data obj %}</h3></p>

                    </td>
                </tr>

            {% endfor %}
        </table>
    {% endblock content %}


    </body>
</html>

products/templates/products/products_form.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
    <div class="col-6 ">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить товар{% else %}Создать товар{% endif %}"  &raquo;>
                </form>
                <div class="card-footer">
                    <a href="{% url 'products:products' %}" class="btn btn-primary">Главная</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/products_form_with_formset.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
<div class="col">
<form  method="post" enctype="multipart/form-data" class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
             <table class="table"
                    <tr class="version-form">
                    {% csrf_token %}
                   <td>{{  form.as_p }}</td>
                    </tr>
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить товар{% else %}Создать товар{% endif %}"  &raquo;>
                <div class="card-footer">
                    <a href="{% url 'products:products' %}" class="btn btn-primary">Главная</a>
                </div>
                    </table>
            </div>
        </div>

    </div>
    <div class="col-3">
        <div class="card-header">
            Версии
        </div>
        <div class="card-body">
            <table class="table">
               {{ formset.management_form }}
                {% for form in formset.forms%}
                    <tr class="version-form">
                        <td>{{  form.as_p }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

</form>
{% endblock %}

products/templates/products/products_list.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}

<h1>{{ text }}</h1>
<diov class="col-12">
    <a href="{% url 'products:product_create' %}" class ='btn btn-primary' m-2>Создать товар &raquo;</a>
</diov>
<diov class="col-12">
    <a href="{% url 'products:products_not_published' %}" class ='btn btn-primary' m-2>Неопубликованные товары &raquo;</a>
</diov>
<diov class="col-12">
    <a href="{% url 'products:categories' %}" class ='btn btn-primary' m-2>Все категории &raquo;</a>
</diov>
      <div class="container">
         <div class="row">
    {% for object in object_list %}
    <div class="col-sm-4">
      <div class="card">
            <div class="card-header">
                {% if  object.image %}
                <img src={{ object.image.url }} alt={{ object.name }} class="img-fluid rounded-start" width="100" height="100">
                {% endif %}
            </div>

              <div class="card-body">
                <h3 class="card-title">{{ object.name }}</h3>
                    <h3 class="card-text" href={% url 'products:category' object.category.pk %}>{{ object.category }} </h3>
                    <!-- <a class="btn btn-warning" href={% url 'products:category_update' object.category.pk %}>Изменить &raquo;</a> -->

                    <p class="card-text">{{ object.description|cut_first }}</p>
                    <p class="card-text">{% get_ruble object.price %}</p>
                    <p class="card-text">Дата создания: {{ object.created_data|date:'d:m:Y' }}</p>
                    <p class="card-text">Дата последнего изменения: {{ object.last_changed_data|date:'d:m:Y' }}</p>
                    <p class="card-text">Автор: {{ object.user }}</p>
                    <a class="btn btn-secondary" href={% url 'products:product' object.pk %}>Перейти &raquo;</a>
                  {%  if perms.products.change_products %}
                    <a class="btn btn-warning" href={% url 'products:product_update' object.pk %}>Изменить &raquo;</a>
                  {% endif %}
                  {%  if perms.products.delete_products %}
                    <a class="btn btn-danger" href={% url 'products:product_delete' object.pk %}>Удалить &raquo;</a>
                  {% endif %}
              </div>
            </div>
      </div>
{% endfor %}
    </div>
        </div>
{% endblock content %}

products/templates/products/version_detail.html
{% extends 'products/base.html' %}
{% block content %}
<h3>{{  text }}</h3>
{% include "products/includes/version.html" %}

    <diov class="col-12">
        <a href="{% url 'products:version_create' %}" class ='btn btn-primary' m-2>Создать версию &raquo;</a>
    </diov>
    <a href="{% url 'products:toggle_activity_version' object.pk %}" class="btn btn-warning float-rigth">
            {% if object.is_active %}Деактивировать
            {% else %}Активировать
            {% endif %} &raquo;</a>

    <a href="{% url 'products:products' %}" class="btn btn-primary">Главная &raquo;</a>

{% endblock content %}

products/templates/products/version_form.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
<div class="form-check-inline">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить версию{% else %}Создать версию{% endif %}"  &raquo;>
                </form>
                <div class="card-footer">
                    <a href="{% url 'products:versions' %}" class="btn btn-primary">Все версии</a>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

products/templates/products/version_form_with_formset.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}
<div class="col">
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <table class="table"
                    <tr class="products-form">
                        {% csrf_token %}
                        <td>{{ form.as_p }}</td>
                    </tr>
                </table>
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить версию{% else %}Создать версию{% endif %}"  &raquo;>
                    <div class="card-footer">
                        <a href="{% url 'products:versions' %}" class="btn btn-primary">Все версии</a>
                    </div>
            </div>
        </div>
    </div>

</div>
</form>
{% endblock %}

products/templates/products/version_list.html
{% extends 'products/base.html' %}
{% load functions %}

{% block content %}

<h1>{{ text }}</h1>
<diov class="col-12">
    <a href="{% url 'products:version_create' %}" class ='btn btn-primary' m-2>Создать версию &raquo;</a>
</diov>
<diov class="col-12">
    <a href="{% url 'products:versions' %}" class ='btn btn-primary' m-2>Все версии &raquo;</a>
</diov>
<diov class="col-12">
    <a href="{% url 'products:versions_draft' %}" class ='btn btn-primary' m-2>Удаленные версии &raquo;</a>
</diov>
      <div class="container">
         <div class="row">
         {% if  versions %}
            {% for object in versions %}
                {% include "products/includes/version.html" %}
            {% endfor %}
         {% else %}
             <br>
            <h4>Нет ни одной версии</h4>
         {% endif %}
    </div>
        </div>
{% endblock content %}